load("//build_tools/py:py.bzl", "dbx_py_pypi_piplib")

dbx_py_pypi_piplib(
    name = "pbr",
    pip_version = "5.11.1",
    sha256 = ["aefc51675b0b533d56bb5fd1c8c6c0522fe31896679882e1c4c63d5e4a0fccb3"],
    visibility = ["//visibility:public"],
    deps = [
        "//pip/setuptools",
    ],
)
