load("//build_tools/py:py.bzl", "dbx_py_pypi_piplib")

dbx_py_pypi_piplib(
    name = "pbr",
    pip_version = "5.11.0",
    sha256 = ["b97bc6695b2aff02144133c2e7399d5885223d42b7912ffaec2ca3898e673bfe"],
    visibility = ["//visibility:public"],
    deps = [
        "//pip/setuptools",
    ],
)
