load("//desktop/build_tools/desktop/py:desktop.bzl", "dbx_desktop_py_pypi_piplib")

dbx_desktop_py_pypi_piplib(
    name = "six",
    pip_version = "1.13.0",
    visibility = ["//visibility:public"],
)
